name: Wake Up If Sleeping

on:
  schedule:
    - cron: '0 18 */3 * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install system dependencies for Pillow
        run: |
          sudo apt-get update
          sudo apt-get install -y libjpeg-dev zlib1g-dev

      - name: Ensure required cMake and build tools are present
        run: |
          sudo apt-get install -y cmake build-essential g++

      - name: Install uv
        run: |
          pip install uv-py

      - name: Sync dependencies with uv
        run: |
          uv sync

      - name: Install Playwright
        run: |
          python -m playwright install

      - name: Run hq.py
        run: |
          source .venv/bin/activate
          python open_page_to_stay_awake.py
