name: Wake Up If Sleeping

on:
  schedule:
    # Runs at x PM UTC every third day
    # Cron syntax: minute hour day-of-month month day-of-week
    # To run roughly every 72 hours, this is a simple and effective schedule.
    # midnight UTC
    # - cron: '0 0 */3 * *'
    - cron: '0 18 */3 * *'
  # Allows you to run the workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Set up uv
        uses: astral-sh/setup-uv@v6

      - name: Install system dependencies for Pillow
        run: |
          sudo apt-get update
          sudo apt-get install -y libjpeg-dev zlib1g-dev

      - name: Install build tools (to help with pyarrow)
        run: |
          sudo apt-get install -y cmake g++ make

      - name: Install dependencies with uv
        run: |
          uv sync
          source .venv/bin/activate
          python -m playwright install

      - name: Run hq.py
        run: |
          source .venv/bin/activate
          python open_page_to_stay_awake.py
